name: URL Link Checks
on:
  page_build: # trigger on page_build for GitHub Pages
  schedule:
    - cron: "0 0 1 * *" # run monthly
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "*.html,*.md"
          markdown: true
          recurse: true
          linksToSkip: "node_modules/,assets/,synectics/,styles/,https://www.linkedin.com/*"
