name: Repository Dispatch

on:
  repository_dispatch:
    types: [synectic-release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          awk -v block='
          <span> ORS\
            <h3>${{ github.event.client_payload.version }}</h3> ORS\
            <span class="venue"> ORS\
              <ul> ORS\
                <li> ORS\
                  <h4> ORS\
                    <a href="https://github.com/EPICLab/synectic/releases/tag/v${{ github.event.client_payload.version }}">Release Notes</a> ORS\
                  </h4> ORS\
                </li> ORS\
                <li> ORS\
                  <h4>Downloads:</h4> ORS\
                  <a href="https://github.com/EPICLab/synectic/releases/download/v${{ github.event.client_payload.version }}/Synectic-${{ github.event.client_payload.version }}-x64.dmg"> ORS\
                    <i class="fab fa-apple"></i> MacOS</a> | ORS\
                  <a href="https://github.com/EPICLab/synectic/releases/download/v${{ github.event.client_payload.version }}/Synectic-${{ github.event.client_payload.version }}.Setup.exe"> ORS\
                    <i class="fab fa-windows"></i> Windows</a> | ORS\
                  <a href="https://github.com/EPICLab/synectic/releases/download/v${{ github.event.client_payload.version }}/Synectic-${{ github.event.client_payload.version }}-full.nupkg"> ORS\
                    <i class="fas fa-cube"></i> NuGet</a> | ORS\
                  <a href="https://github.com/EPICLab/synectic/releases/download/v${{ github.event.client_payload.version }}/synectic_${{ github.event.client_payload.version }}_amd64.deb"> ORS\
                    <i class="fab fa-linux"></i> deb</a> | ORS\
                  <a href="https://github.com/EPICLab/synectic/releases/download/v${{ github.event.client_payload.version }}/synectic-${{ github.event.client_payload.version }}-1.x86_64.rpm"> ORS\
                    <i class="fab fa-linux"></i> RPM</a> ORS\
                </li> ORS\
              </ul> ORS\
            </span> ORS\
          </span> ORS\
          <br />' '{ print } /<h2>Releases<\/h2>\n.*?<table class="table">\n.*?<tbody>\n.*?<tr>\n.*?<td>\n.*?<span>/ { print block }' synectic.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Synectic ${{ github.event.client_payload.version }} release"
          git push
