name: Repository Dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubnutu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo ${{ github.event.client_payload.version }}
